[package]
name = "kraken"
version = "0.0.1"
authors = ["ethanshry <ehshry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.14.2"
juniper_rocket = "0.5.1"
rocket = "0.4.2"
serde = "1.0.106"
serde_json = "1.0.41"
sysinfo = "0.14.1"
amiquip = { version = "0.3", default-features = false }
uuid = { version = "0.8", features = ["serde", "v4"] }
reqwest = "0.10.4"
toml = "0.4.2"